title: Lerntagebuch Bibliotheks- und Archivinformatik
author: stemorit
description: > # this means to ignore newlines until "baseurl:"
  Ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik für den Bachelorstudiengang in Informatio Science an der FH Graubünden.



show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-tactile
